version: '3'

services:

  app:
    build: .
    ports:
      - 8080:80
    expose:
      - 9000
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - .:/home/repobrowser/project
      - ./docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpass}
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_HOST: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw
volumes:
  db-data:
    
